### ISSUE TITLE
Not resolved jwtHandler.Serve

### ISSUE THREAD

**Issue by Mahdihp** [iris-contrib/middleware#49] opened 2019-06-01 15:55 UTC
Not resolved jwtHandler.Serve when use Jwt Middelware:
`app := iris.New()
jwtHandler := jwtmiddleware.New(jwtmiddleware.Config{
		ValidationKeyGetter: func(token *jwt.Token) (interface{}, error) {
			return []byte("My Secret"), nil
		},
		SigningMethod: jwt.SigningMethodHS256,
	})
app.Use(jwtHandler.Serve)`

**Comment by kataras** [comment] 2019-06-25 16:29
Duplicate of: https://github.com/kataras/iris/issues/1269

**Closed** 2019-06-25 16:29 UTC
Labels: duplicate
